### ISSUE TITLE
Missing ES2015 preset?

### ISSUE THREAD

**Issue by morerunes** [luisfarzati/express-babelify-middleware#6]
Hey, I pulled this into my project and tried serving up some JS, just like I was doing earlier (successfully) with browserify-middleware, and I got a missing preset error. Any idea what's up?

`Error: Couldn't find preset "es2015" relative to directory "/Users/aaronechols/IdeaProjects/morerunes.com/lib/static/js_src" while parsing file: /Users/aaronechols/IdeaProjects/morerunes.com/lib/static/js_src/browserify-test-lib.js
   at /Users/aaronechols/IdeaProjects/morerunes.com/node_modules/express-babelify-middleware/node_modules/babelify/node_modules/babel-core/lib/transformation/file/options/option-manager.js:281:17
   at Array.map (native)
   at OptionManager.resolvePresets (/Users/aaronechols/IdeaProjects/morerunes.com/node_modules/express-babelify-middleware/node_modules/babelify/node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:20)
   at OptionManager.mergePresets (/Users/aaronechols/IdeaProjects/morerunes.com/node_modules/express-babelify-middleware/node_modules/babelify/node_modules/babel-core/lib/transformation/file/options/option-manager.js:254:10)
   at OptionManager.mergeOptions (/Users/aaronechols/IdeaProjects/morerunes.com/node_modules/express-babelify-middleware/node_modules/babelify/node_modules/babel-core/lib/transformation/file/options/option-manager.js:239:14)
   at OptionManager.init (/Users/aaronechols/IdeaProjects/morerunes.com/node_modules/express-babelify-middleware/node_modules/babelify/node_modules/babel-core/lib/transformation/file/options/option-manager.js:338:12)
   at File.initOptions (/Users/aaronechols/IdeaProjects/morerunes.com/node_modules/express-babelify-middleware/node_modules/babelify/node_modules/babel-core/lib/transformation/file/index.js:216:65)
   at new File (/Users/aaronechols/IdeaProjects/morerunes.com/node_modules/express-babelify-middleware/node_modules/babelify/node_modules/babel-core/lib/transformation/file/index.js:137:24)
   at Pipeline.transform (/Users/aaronechols/IdeaProjects/morerunes.com/node_modules/express-babelify-middleware/node_modules/babelify/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
   at Babelify._flush (/Users/aaronechols/IdeaProjects/morerunes.com/node_modules/express-babelify-middleware/node_modules/babelify/index.js:27:24)`

**Comment by lufzle** [comment]
Do you have `babel-preset-es2015` installed in your modules? It's a mandatory default unless you specify a different preset in `babelifyOptions` like this:

```
babelify('public/app.js', undefined, {
  presets: ['some_other_presets']
})
```
